{{ range $service, $def := .Values.services }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $service }}
  namespace: argocd
{{/*  finalizers:*/}}
{{/*    - resources-finalizer.argocd.argoproj.io*/}}
spec:
  description: {{ $def.description }}

  sourceRepos:
    - 'https://github.com/third-place/{{ $def.repository }}.git'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
    - namespace: {{ $service }}
      server: https://kubernetes.default.svc
    {{- if $def.hasSubcomponents }}
    - namespace: '*'
      server: https://kubernetes.default.svc
    {{ end }}

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    {{- if $def.hasSubcomponents }}
    - group: ''
      kind: Namespace
    {{ end }}

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true
---
{{ end }}