{{ range $service, $def := .Values.services }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $service }}
  namespace: argocd
spec:
  description: {{ $def.description }}

  sourceRepos:
    - https://github.com/third-place/{{ $def.repository }}.git
    - ghcr.io/third-place

  destinations:
    {{- if $def.isRegistry }}
    - namespace: '*'
      server: https://kubernetes.default.svc
    {{ else }}
    - namespace: {{ $service }}
      server: https://kubernetes.default.svc
    {{ end }}
    {{- if (eq $service "cert-manager") }}
    - namespace: kube-system
      server: https://kubernetes.default.svc
    {{- end }}

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    {{- if $def.isRegistry }}
    - group: ''
      kind: Namespace
    {{ end }}
    {{- if (eq $service "cert-manager") }}
    - group: ''
      kind: ClusterIssuer
    {{ end }}
    {{- if (eq $service "sealed-secrets") }}
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: CustomResourceDefinition
    {{ end }}
    {{- if (eq $service "kafka") }}
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    {{ end }}
    {{- if (eq $service "ingress") }}
    - group: '*'
      kind: ValidatingWebhookConfiguration
    - group: '*'
      kind: IngressClass
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: ClusterRole
    {{- end }}
    {{- if (eq $service "metallb") }}
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: ValidatingWebhookConfiguration
    {{- end }}
    {{- if (eq $service "external-dns") }}
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    {{- end }}
    {{- if (eq $service "cert-manager") }}
    - group: '*'
      kind: ClusterIssuer
    - group: '*'
      kind: ValidatingWebhookConfiguration
    - group: '*'
      kind: MutatingWebhookConfiguration
    - group: '*'
      kind: Role
    - group: '*'
      kind: RoleBinding
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: CustomResourceDefinition
    {{- end }}
    {{- if (eq $service "gatekeeper") }}
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ValidatingWebhookConfiguration
    - group: '*'
      kind: MutatingWebhookConfiguration
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: ConstraintTemplate
    - group: 'constraints.gatekeeper.sh'
      kind: K8sContainerRequests
    - group: 'constraints.gatekeeper.sh'
      kind: K8sContainerLimits
    - group: 'constraints.gatekeeper.sh'
      kind: K8sHorizontalPodAutoscaler
    - group: 'constraints.gatekeeper.sh'
      kind: K8sPodDisruptionBudget
    {{- end }}

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true
---
{{ end }}