{{ range $service, $def := .Values.services }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $service }}
  namespace: argocd
spec:
  description: {{ $def.description }}

  sourceRepos:
    - https://github.com/third-place/{{ $def.repository }}.git
    - ghcr.io/third-place/platform

  destinations:
    - namespace: {{ $service }}
      server: https://kubernetes.default.svc
    {{- if $def.hasSubcomponents }}
    - namespace: '*'
      server: https://kubernetes.default.svc
    {{ end }}

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    {{- if $def.hasSubcomponents }}
    - group: ''
      kind: Namespace
    {{ end }}
    {{- if (eq $service "cert-manager") }}
    - group: ''
      kind: ClusterIssuer
    {{ end }}
    {{- if (eq $service "sealed-secrets") }}
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: CustomResourceDefinition
    {{ end }}
    {{- if (eq $service "kafka") }}
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    {{ end }}
    {{- if (eq $service "ingress") }}
    - group: '*'
      kind: ValidatingWebhookConfiguration
    - group: '*'
      kind: IngressClass
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: ClusterRole
    {{- end }}
    {{- if (eq $service "metallb") }}
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: '*'
      kind: ValidatingWebhookConfiguration
    {{- end }}

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true
---
{{ end }}