{{ range $service, $def := .Values.services }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $service }}
  {{- if $def.namespace.labels }}
  labels:
    {{ toYaml $def.namespace.labels | nindent 4 }}
  {{- end }}
---
{{ end }}
