apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Release.Name }}
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/third-place/platform.git
    - ghcr.io/third-place

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  orphanedResources:
    warn: true
