apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  labels:
    app: registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registries
          image: {{ .Values.repository }}:{{ .Values.version }}
          env:
            - name: REGISTRIES
              value: {{ .Values.registries | toJson | quote }}
