services:
  system:
    repository: platform
    directory: system
    ref: main
    description: Main platform dependencies
    hasSubcomponents: true
  applications:
    repository: platform
    directory: applications
    ref: main
    description: Services that make up the application
    hasSubcomponents: true
