{{ if .Values.enabled }}
{{ $name := include "name" . }}
{{ range $secret, $entry := .Values.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}-{{ kebabcase $secret }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
spec:
  encryptedData:
    secretValue: {{ $entry }}
---
{{ end }}
{{ end }}
