{{ $clusterName := .Values.clusterName }}
{{ range $topic := .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $topic }}
  labels:
    strimzi.io/cluster: {{ $clusterName }}
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
{{ end }}