registry:
  services:
    backstage:
      repository: backstage
      directory: chart
      ref: main
      description: Backstage
    user-service:
      repository: user-service
      directory: chart
      ref: main
      description: User service
    image-service:
      repository: image-service
      directory: chart
      ref: main
      description: Image service
