name: infra
apiVersion: v2
version: 0.0.1
dependencies:
  - name: registry
    version: 0.0.26
    repository: file://../registry
  - name: cert-manager
    version: 1.14.4
    repository: https://charts.jetstack.io
