registry:
  services:
    sealed-secrets:
      repository: platform
      directory: sealed-secrets
      ref: main
      description: Sealed secrets
    kafka:
      repository: platform
      directory: kafka
      ref: main
      description: Kafka
    cluster-issuer:
      repository: platform
      directory: cluster-issuer
      ref: main
      description: Cluster issuer
