port:
targetPort:
nodePort:
secrets:
enabled: true
serviceType: NodePort
postgres:
  enabled: false
  auth:
    username:
    database:
env:
ingress:
  enabled: false
  host:
  paths:
externalDns:
  enabled: false
nfsVolumes:
resources:
  requests:
    memory:
    cpu:
  limits:
    memory:
    cpu: 
