port:
targetPort:
nodePort:
secrets:
enabled: true
serviceType: LoadBalancer
postgres:
  enabled: false
  auth:
    username:
    database:
env:
ingress:
  enabled: false
  host:
  paths:
externalDns:
  enabled: false
