port:
targetPort:
nodePort:
secrets:
enabled: true
serviceType: NodePort
postgres:
  enabled: false
  auth:
    username:
    database:
env:
ingress:
  enabled: false
  host:
  paths:
externalDns:
  enabled: false
nfsVolumes:
  - name: images
    server: 192.168.254.30
    path: /k8s/images
    mountPath: /var/images
