{{ if (and .Values.enabled (not .Values.selfSigned)) }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: thirdplace-letsencrypt-{{ .Values.global.env }}
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: dan@danmunro.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: thirdplace-letsencrypt-{{ .Values.global.env }}
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: traefik
{{ end }}