{{ if .Values.enableClusterIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: thirdplace-letsencrypt-{{ .Values.global.env }}
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dan@danmunro.com
    privateKeySecretRef:
      name: thirdplace-letsencrypt-{{ .Values.global.env }}
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik
{{ end }}