{{ $serviceVersion := "" }}
{{ $name := .Values.name }}
{{ range $service, $version := .Values.global.versions }}
{{ if eq $name $service }}
{{ $serviceVersion = $version }}
{{ end }}
{{ end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: ghcr.io/third-place/{{ .Values.name }}:{{ $serviceVersion }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.targetPort }}
              name: http
              protocol: TCP

