{{ $releaseName := .Release.Name }}
{{ $port := .Values.port }}
{{ $paths := .Values.ingress.paths }}
{{ $host := printf "%s.%s" .Release.Name .Values.global.fqdn }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $releaseName }}-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ default .Values.ingress.host $host }}
      http:
        paths:
          {{- range $path := $paths }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $releaseName }}
                port:
                  number: {{ $port }}
          {{- end }}
{{- end }}