{{ $releaseName := .Release.Name }}
{{ $port := .Values.port }}
{{ $paths := .Values.ingress.paths }}
{{ $host := printf "%s.%s" .Release.Name .Values.global.fqdn }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $releaseName }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: thirdplace-letsencrypt-{{ .Values.global.env }}
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: {{ default $host .Values.ingress.host }}
      http:
        paths:
          {{- range $path := $paths }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $releaseName }}
                port:
                  number: {{ $port }}
          {{- end }}
  tls:
    - hosts:
      - {{ default $host .Values.ingress.host }}
      secretName: thirdplace-letsencrypt-{{ .Values.global.env }}
{{- end }}