{{ $releaseName := .Release.Name }}
{{ $targetPort := .Values.targetPort }}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $releaseName }}-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          {{- range $path := .Values.ingress.paths }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $releaseName }}
                port:
                  number: {{ $targetPort }}
          {{- end }}
{{- end }}