{{ if .Values.postgresql.enabled }}
{{ $name := .Release.Name }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret }}
  namespace: {{ $name }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
spec:
  encryptedData:
    postgres-password: {{ .Values.postgresql.auth.secretPassword }}
    password: {{ .Values.postgresql.auth.secretPassword }}
{{ end }}
