{{ $name := .Release.Name }}
{{ range $secret, $entry := .Values.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ kebabcase $secret }}
  namespace: {{ $name }}
spec:
  encryptedData:
    secretValue: {{ $entry }}
---
{{ end }}