apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.targetPort }}