{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- if .Values.externalDns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}.{{ .Values.global.fqdn }}
    {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.serviceType }}
  ports:
    - name: http
      port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.targetPort }}
      nodePort: {{ .Values.nodePort }}
{{- end }}
