registry:
  services:
#    cert-manager:
#      repository: platform
#      directory: cert-manager
#      ref: main
#      description: Let's encrypt cert manager
    ingress:
      repository: platform
      directory: ingress
      ref: main
      description: Nginx ingress
    sealed-secrets:
      repository: platform
      directory: sealed-secrets
      ref: main
      description: Sealed secrets
    kafka:
      repository: platform
      directory: kafka
      ref: main
      description: Kafka
    applications:
      repository: platform
      directory: applications
      ref: main
      description: Services that make up the application
      hasSubcomponents: true