appPath:
registry:
  services: []
#    sealed-secrets:
#      repository: platform
#      directory: sealed-secrets
#      ref: main
#      description: Sealed secrets
#    kafka:
#      repository: platform
#      directory: kafka
#      ref: main
#      description: Kafka
#    applications:
#      repository: platform
#      directory: applications
#      ref: main
#      description: Services that make up the application
#      hasSubcomponents: true
global:
  env:
  fqdn:
