argo-cd:
  configs:
    params:
      server.insecure: true

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      tls: true

