apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name}}-postgres
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgres
      port: 5432
      targetPort: tcp-postgres
  selector:
    app.kubernetes.io/component: primary
