apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: argocd

spec:
  project: {{ .Release.Name }}

  source:
    repoURL: https://github.com/third-place/platform.git
    targetRevision: main
    path: platform

    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
        {{- if eq .Values.environment "dev" }}
        - values.dev.yaml
        {{- end }}
        {{- if eq .Values.environment "staging" }}
        - values.staging.yaml
        {{- end }}
        {{- if eq .Values.environment "prod" }}
        - values.prod.yaml
        {{- end }}
      values: |
        global:
          environment: {{ .Values.environment }}

  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
