on:
  push:
    branches:
      - main
    paths:
      - service/**
jobs:
  publish-service-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.HELM_REPO_TOKEN }} | helm registry login ghcr.io -u ${{ secrets.HELM_CHART_USER }} --password-stdin
      - run: helm dependency update service/
      - run: helm package service/
      - run: helm push *.tgz oci://ghcr.io/third-place