on:
  push:
    branches:
      - main
    paths:
      - service/**
jobs:
  publish-service-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ secrets.HELM_REPO_TOKEN }} | helm registry login c8n.io -u ${{ secrets.HELM_CHART_USER }} --password-stdin
      - run: helm package service/
      - run: helm push *.tgz oci://c8n.io/third-place